config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home', as: :home
  devise_for :users 
  get '/show_user/:id' => 'pages#show_user', as: :show_user

  resources :books do 
    collection do
      get 'lend_requests'
      get 'return_requests'
      get 'lended_list'
      get 'searched_index'
      get 'thank'
    end
    get 'lend', on: :member
    get 'return', on: :member
  end

  resources :librarians, only: [:index, :show] do 
    get 'books', on: :collection
  end

  resources :user_admins, only: [:index, :show, :destroy]
  resources :request_admins, only: [:index, :show] do
    member do
      get 'pending'
      get 'approved'
      get 'rejected'
      get 'approve_lend'
      get 'reject_lend'
      get 'approve_return'
      get 'reject_return'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

	has_many :lended_book, dependent: :destroy

	has_many :requests, dependent: :destroy
	before_create :set_available_books
	validate do 
		# puts "book id(in book model): #{self.id}"
		# puts "Available books(in book model): #{self.availableBooks}"
		# puts "Title(in book model): #{self.title}"
		if (self.availableBooks>self.totalBooks)
			self.errors.add(:availableBooks, "Should not be greater than Total Books")
		end
	end
	validates :title, presence: true
	validates :author, presence: true
	validates :publisher, presence: true
	validates :language, presence: true
	validates :description, presence: true

	def set_available_books
		self.availableBooks = self.totalBooks
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action -> { check_repeating_requests("lend") }, only: [:lend]
	before_action -> { check_repeating_requests("return") }, only:[:return]
	def index
		@books = Book.paginate(page: params[:page], per_page: 5)
		#render json:Book.all
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.valid?
			if @book.save 
				redirect_to librarian_path(@book.id), notice: "Book Added"
			end
		else 
			render :new
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		# puts "Available books(in book controller):#{@book.availableBooks}"
		#puts @book.totalBooks
		if @book.update(title: params[:book][:title], author: params[:book][:author], publisher: params[:book][:publisher], language: params[:book][:language], description: params[:book][:description], totalBooks: params[:book][:totalBooks], availableBooks: params[:book][:availableBooks])
			redirect_to librarian_path(@book), notice: "Book Updated"
		else
			render :edit
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def destroy
		Book.find(params[:id]).destroy
		redirect_to books_librarians_path, notice: "Book deleted"
	end

	


	def searched_index
		@books = Book.where('title LIKE ?', "%#{params[:search]}%").paginate(page: params[:page], per_page: 5)
	end

	def lended_list
	    @lended_books=LendedBook.where(user_id: current_user.id).where.not(status: "Returned").paginate(page: params[:page], per_page: 10)
	end
	def thank

	end
	def lend
		Request.create(status: "Pending", request_type: "lend", user_id: current_user.id, book_id: params[:id])
		redirect_to thank_books_path
	end

	def return
		lended_book = LendedBook.find(params[:id])
		lended_book.update(status: "Returning")
		request = Request.create(status: "Pending", request_type: "return", user_id: current_user.id, book_id: lended_book.book_id, lended_book_id: lended_book.id)
		
		redirect_to thank_books_path
	end

	def lend_requests
		@requests = Request.where(user_id: current_user.id, request_type: "lend").order(:status).paginate(page: params[:page], per_page: 10)
		@books = Book.all

	end

	def return_requests
		@requests = Request.where(user_id: current_user.id, request_type: "return").order(:status).paginate(page: params[:page], per_page: 10)
		@books = Book.all

	end


	private
	def book_params
		params.require(:book).permit(:title, :author, :publisher, :language, :description, :totalBooks, :availableBooks, :image)
	end

	def check_repeating_requests(request_type)
		repeating_requests = Request.where(book_id: params[:id], user_id: current_user.id, status: "Pending", request_type: request_type)
		if !repeating_requests.empty? 
			redirect_to books_path, notice: "Same Lending Request has been made Already"
		end
		if request_type=="lend"
			lended_books= LendedBook.where(book_id: params[:id], user_id: current_user.id, status: "Holding").or(LendedBook.where(book_id: params[:id], user_id: current_user.id, status: "Returning"))
			if !lended_books.empty?
				redirect_to books_path, notice: "Same Book is being hold by you"
			end
		end
	end
end

app/helpers/books_helper.rb
module BooksHelper
	def  errors_for(form, field)
		content_tag(:p, form.object.errors[field].try(:first))
	end

	def form_group_for(form, field, opts={}, &block)
		has_errors = form.object.errors[field].present?

		content_tag :div do 
			concat capture(&block)
			concat errors_for(form, field)
		end
	end
end

app/views/books/edit.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>

	<div class="librarianContainer" >
		<center>
			<div class="librarianBookEditBox">
				<% if !@book.errors.messages.empty? %>
					<ul style="color: red; font-size: 25px; align-self: center;" >
						<% @book.errors.messages.each do |label, messages| %>
							<% messages.each do |message| %>
								<li> <%= "#{label.to_s.capitalize} #{message}" %> </li>
							<% end %>
						<% end %>
					</ul>
				<% end %>
				<%= form_for @book do |f| %>
					<table class="librarianBookEditTable">
						<tr>
							<td> <%= f.label :title %> </td>
							<td> <%= f.text_field :title, presence: true %>
						</tr>
						<tr>
							<td> <%= f.label :author %> </td>
							<td> <%= f.text_field :author, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :publisher %> </td>
							<td> <%= f.text_field :publisher, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :language %> </td>
							<td> <%= f.text_field :language, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :description %> </td>
							<td> <%= f.text_area :description, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :total_books %> </td>
							<td> <%= f.text_field :totalBooks, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :available_books %> </td>
							<td> <%= f.text_field :availableBooks, presence: true  %> </td>
						</tr>
						<tr>
							<td> <%= f.label :image_path %> </td>
							<td> <%= f.text_field :image, presence: true  %> </td>
						</tr>
					</table>

					<%= f.submit "Save Changes", class: 'librarianBookEditButton' %>

				<% end %>
			</div>

		</center>
	</div>


	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/index.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Title") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>

	<div class="container" >
		<% @books.each do |book| %>
			<center>
				<%= link_to book_path(book) do %>
					<div class="thumbnail">
						<img src='<%= book.image %>' >
						<div class="caption">
							<h3 class="title"> <%= book.title %></h3>
							<p class="author"><%= book.author %></p>
						</div>
					</div>
				<% end %>
			</center>
			<br><br><br><br>
		<% end %>

	</div>
	<center>
			<%= will_paginate @books, class: "digg_pagination"%>
	</center>

	<br><br><br><br><br><br><br><br><br>
	

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/lend_requests.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				
				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>


	<div class="container" >
		<center>
			<div class="requestsTabs">
				<a class= "requestsTabAnchor" href='/books/lend_requests' >
					<div class="requestsTabActive">
						Lend Requests
					</div>
				</a>
				<a class= "requestsTabAnchor" href='/books/return_requests' >
					<div class="requestsTab">
						Return Requests
					</div>
				</a>
			</div>

			<br><br>

			<div class= "requestsBox"> 
				<% if @requests.empty? %>
					<br><br><br>
					<h1> No Requests for lending Books </h1>
				<% else %>
					<table>
							<tr>
								<th id="t1"> S.No. </th>
								<th id="t2"> Book </th>
								<th id="t3"> Available <br> Books </th>
								<th id="t4"> Status </th>
							</tr>
						<% count = ((params[:page]||1).to_i - 1) * 10 %>
						<% @requests.each_with_index do |request, index| %>
							<% book = @books.find(request.book_id) %>
							<tr>
								<td> <%= count + index + 1 %></td>
								<td> <%= book.title %> </td>
								<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
								<td> <%= request.status %> </td>
							</tr>
						<% end %>
					</table>
				<% end %>
			</div>

			<%= will_paginate @requests, class: "digg_pagination" %>
		</center>
	</div>



	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/lended_list.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>
	</div>

	<div class="container" >
		<center>
			<div class= "lendedBookBox">
				<% if @lended_books.empty? %>
					<h1 style="color: black;"> No Books are lended </h1>
				<% else %>
					<table>
						<tr >
							<th id="t1">S.No.</th>
							<th id="t2">Title</th>
							<th id="t3">Date Of Lending</th>
							<th id="t4">Return</th>
						</tr>
						<% count = ((params[:page]||1).to_i - 1) * 10 %>
						<% @lended_books.each_with_index do |lended_book, index| %>
							<tr>
								<td> <%= count + index + 1 %> </td>
								<td> <%= lended_book.name %> </td>
								<td> <%= lended_book.date_of_lend.strftime("%Y-%m-%d") %> </td>
								<td> 
									<% if lended_book.status == "Holding" %>
										<%= link_to  "Return", return_book_path(lended_book) %>
									<% else %>
										<%= lended_book.status %>
									<% end %>
								</td>
							</tr>
						<% end %>
					</table>
				<% end %>
			</div>
			<%= will_paginate @lended_books, class: "digg_pagination"%>

		</center>

	</div>

	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/new.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>

	<div class="librarianContainer" >
		<center>
			<h1> Add New Book </h1>
			<div class="librarianBookEditBox">
				
				<%= form_with model: @book do |f| %>
				<% if !@book.errors.messages.empty? %>
					<ul>
						<% @book.errors.messages.each do |label, messages| %>
							<% messages.each do |message| %>
								<li> <%= label.to_s_capitalize + message %> </li>
							<% end %>
						<% end %>
					</ul>
				<% end %>
					<table class="librarianBookEditTable">
						<tr>
							<td> <%= f.label :title %> </td>
							<td> <%= f.text_field :title, required: true %>
						</tr>
						<tr>
							<td> <%= f.label :author %> </td>
							<td> <%= f.text_field :author, required: true %> </td>
						</tr>
						<tr>
							<td> <%= f.label :publisher %> </td>
							<td> <%= f.text_field :publisher, required: true %> </td>
						</tr>
						<tr>
							<td> <%= f.label :language %> </td>
							<td> <%= f.text_field :language, required: true %> </td>
						</tr>
						<tr>
							<td> <%= f.label :description %> </td>
							<td> <%= f.text_area :description, size: "18x4", required: true %> </td>
						</tr>
						<tr>
							<td> <%= f.label :image_path %> </td>
							<td> <%= f.text_field :image, value: "/assets/bookLogo.jpg", required: true%> </td>
						</tr>
						<tr>
							<td> <%= f.label :total_books %> </td>
							<td> <%= f.text_field :totalBooks, value: 0, required: true%> </td>
						</tr>
					</table>

					<%= f.submit "Add Book"%>

				<% end %>
			</div>

		</center>
	</div>


	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/return_requests.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>


	<div class="container" >
		<center>
			<div class="requestsTabs">
				<a class= "requestsTabAnchor" href='/books/lend_requests' >
					<div class="requestsTab">
						Lend Requests
					</div>
				</a>
				<a class= "requestsTabAnchor" href='/books/return_requests' >
					<div class="requestsTabActive">
						Return Requests
					</div>
				</a>
			</div>

			<br><br>
			
			<div class= "requestsBox"> 
				<% if @requests.empty? %>
					<br><br><br>
					<h1> No Requests for lending Books </h1>
				<% else %>
					<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> Book </th>
							<th id="t3"> Available <br> Books </th>
							<th id="t4"> Status </th>
						</tr>
						<% count = ((params[:page]||1).to_i - 1) * 10 %>
						<% @requests.each_with_index do |request, index| %>
							<% book = @books.find(request.book_id) %>
							<tr>
								<td> <%= count + index + 1 %></td>
								<td> <%= book.title %> </td>
								<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
								<td> <%= request.status %> </td>
							</tr>
						<% end %>
					</table>
				<% end %>
			</div>

			<%= will_paginate @requests, class: "digg_pagination" %>
		</center>
	</div>



	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/searched_index.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>

	<div class="container" >
			<center>
				<% if @books.empty? %>
					<h1> No Books Found </h1>
				<% else %>
					<% @books.each do |book|%>
						<%= link_to book_path(book) do %>
							<div class="thumbnail">
								<%=image_tag book.image %>
								<div class="caption">
									<h3 class="title"> <%= book.title %></h3>
									<p class="author"><%= book.author %></p>
								</div>
							</div>
						<% end %>

					<br><br><br><br>
					<% end %>
				<% end %>
				
			</center>

	</div>
	<center>
			<%= will_paginate @books, class: "digg_pagination"%>
	</center>

	<br><br><br><br><br><br><br><br><br>


	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/show.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>


	<div class="container" >
		<center>
			<div class="showBlock" >
					<img src="<%=@book.image %>" >
			</div>
			<div class="showDetails">
				<h2>Book Details</h2>
				<table class="bookDetails">
					<tr>
						<td class="TableTag">Title</td>
						<td> : </td>
						<td> <%= @book.title %> </td>
					</tr>
					<tr>
						<td class="TableTag">Author</td>
						<td> : </td>
						<td> <%= @book.author %> </td>
					</tr>
					<tr>
						<td class="TableTag">Publisher </td>
						<td> : </td>
						<td> <%= @book.publisher %> </td>
					</tr>
					<tr>
						<td class="TableTag">Language</td>
						<td> : </td>
						<td> <%= @book.language %> </td>
					</tr>
					<tr>
						<td class="TableTag">Description</td>
						<td> : </td>
						<td> <%= @book.description %> </td>
					</tr>
					<tr>
						<td class="TableTag">Available Quantity</td>
						<td> : </td>
						<td> <%= @book.availableBooks %> </td>
					</tr>
				</table>

			</div>
			<% if @book.availableBooks > 0 %>
				<%= link_to "Lend Book", lend_book_path(@book), class: 'button' %>
			<% else %>
				<h2>No Books Available Right Now</h2>
			<% end %>
		</center>
	</div>


	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/books/thank.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), '/books' , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome,<%= link_to current_user.name, show_user_path(current_user) %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Requests', lend_requests_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'Lended Books', lended_list_books_path %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

			<%= form_tag(searched_index_books_path, method: :get) do %>
				<%= text_field_tag(:search, params[:search] ,:placeholder=>"Search By Name") %>
				<%= submit_tag ("Search") %>
			<% end %>

		</div>

	</div>

	<div class="container" >
		<center>
			<p class="thank"> 
				Thank You!.
				<br>
				Your Request has been posted to LIBRARIAN. Check " Requests " to see status
			</p>
			<p class="goToHome" ><%= link_to "Click here", books_path, class: 'button' %> to go home page</p>
		</center>

	</div>


	<br><br><br><br><br><br><br><br><br>

	
	<div class="footer">
		Visit Soon
	</div>
</div>