config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home', as: :home
  devise_for :users 
  get '/show_user/:id' => 'pages#show_user', as: :show_user

  resources :books do 
    collection do
      get 'lend_requests'
      get 'return_requests'
      get 'lended_list'
      get 'searched_index'
      get 'thank'
    end
    get 'lend', on: :member
    get 'return', on: :member
  end

  resources :librarians, only: [:index, :show] do 
    get 'books', on: :collection
  end

  resources :user_admins, only: [:index, :show, :destroy]
  resources :request_admins, only: [:index, :show] do
    member do
      get 'pending'
      get 'approved'
      get 'rejected'
      get 'approve_lend'
      get 'reject_lend'
      get 'approve_return'
      get 'reject_return'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_admins_controller.rb
class UserAdminsController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.where(role: "member").paginate(page: params[:page], per_page: 10)
	end

	def show #show Users
		@user = User.find(params[:id])
		@lended_books = LendedBook.where(user_id: @user.id).paginate(page: params[:page], per_page: 10)
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to user_admins_path, notice: "User Has Been Removed"
	end

end

app/helpers/user_admins_helper.rb
module UserAdminsHelper
end

app/views/user_admins/index.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<h1> List Of All Users </h1><br>
			<h4>Note:</h4> Click on name to open details
			<div class= "allUsersBox"> 
				<% if @users.empty? %>
				<br><br><br>
					<h1> No Users </h1>
				<% else %>
				<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> User Id </th>
							<th id="t3"> User Name</th>
						</tr> 
					<% count = ((params[:page] || 1).to_i - 1 ) * 10 %>
					<% @users.each_with_index do |user, index| %>
							<tr class="allUsersTableRow">
								<td> <%= count + index + 1%> </td>
								<td> <%= user.id %> </td>
								<td> <%= link_to user.name, user_admin_path(user) %> </td>
							
							</tr>
					<% end %>
				</table>
				<% end %>
				
			</div>
			<br>
			<%= will_paginate @users, class: "digg_pagination" %>
		</center>
	</div>




	<br><br><br><br><br><br><br><br><br>

</div>

app/views/user_admins/show.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.upcase %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>

			<div class="showUserDetails">
				<br><br>
				<h1> USER DETAILS </h1>
				<table class="bookDetails">
					<tr>
						<td class="TableTag"> <b> User Id </b></td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.id %> </td>
					<tr>
						<td class="TableTag"> <b> Name </b></td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.name %> </td>
					</tr>
					<tr>
						<td class="TableTag"> <b>Email</b> </td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.email %> </td>
					</tr>
					<tr>
						<td class="TableTag"><b> Phone </b></td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.phone %> </td>
					</tr>
					<tr>
						<td class="TableTag"> <b>Address</b> </td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.address %> </td>
					</tr>
					<tr>
						<td class="TableTag"> <b>Date Of Membership </b></td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.date_of_membership.strftime("%Y-%m-%d") %> </td>
					</tr>
					<tr>
						<td class="TableTag"> <b>Total Checkouts</b> </td>
						<td> : &nbsp;&nbsp;&nbsp;</td>
						<td> <%= @user.totalcheckout %> </td>
					</tr>
				</table>
				<%= link_to "Remove User", user_admin_path(@user), method: :delete, class: "button", data: {confirm: "SURE?" } %>
				<br><br>
			</div>

			<div class= "lendedBookBox">
				<% if @lended_books.empty? %>
					<h1 style="color: black;"> No Books are lended </h1>
				<% else %>
					<table>
						<tr >
							<th id="t1">S.No.</th>
							<th id="t2">Title</th>
							<th id="t3">Date Of Lending</th>
							<th id="t4">Status</th>
						</tr>
						<% count = ((params[:page] || 1).to_i - 1) * 10%>
						<% @lended_books.each_with_index do |lended_book, index| %>
							<tr>
								<td> <%= count + index + 1%> </td>
								<td> <%= lended_book.name %> </td>
								<td> <%= lended_book.date_of_lend.strftime("%Y-%m-%d") %> </td>
								<td> <%= lended_book.status %> </td>
							</tr>
						<% end %>
					</table>
				<% end %>
			</div>

			<br><br>
			<%= will_paginate @lended_books, class: "digg_pagination" %>
		</center>
	</div>


	<br><br><br><br><br><br><br><br><br>

</div>