config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home', as: :home
  devise_for :users 
  get '/show_user/:id' => 'pages#show_user', as: :show_user

  resources :books do 
    collection do
      get 'lend_requests'
      get 'return_requests'
      get 'lended_list'
      get 'searched_index'
      get 'thank'
    end
    get 'lend', on: :member
    get 'return', on: :member
  end

  resources :librarians, only: [:index, :show] do 
    get 'books', on: :collection
  end

  resources :user_admins, only: [:index, :show, :destroy]
  resources :request_admins, only: [:index, :show] do
    member do
      get 'pending'
      get 'approved'
      get 'rejected'
      get 'approve_lend'
      get 'reject_lend'
      get 'approve_return'
      get 'reject_return'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/request_admins_controller.rb
class RequestAdminsController < ApplicationController
	before_action :authenticate_user!

	def index

	end

	def show
		@type = params[:id]
		@requests =  Request.where(request_type: params[:id]).order(:status).paginate(page: params[:page], per_page: 5)
	end

	def pending
		@books = Book.all
		@users = User.all
		@type = params[:id]
		@requests = Request.where(request_type: params[:id], status: 'Pending').paginate(page: params[:page], per_page: 5)
	end

	def approved
		@books = Book.all
		@users = User.all
		@type = params[:id]
		@requests = Request.where(request_type: params[:id], status: 'Approved').paginate(page: params[:page], per_page: 5)
	end

	def rejected
		@books = Book.all
		@users = User.all
		@type = params[:id]
		@requests = Request.where(request_type: params[:id], status: 'Rejected').paginate(page: params[:page], per_page: 5)
	end

	def approve_lend
		request = Request.find(params[:id])
		book = Book.find(request.book_id)
		user = User.find(request.user_id)
		if book.availableBooks > 0
			book.update(availableBooks: book.availableBooks - 1)
			user.update(totalcheckout: user.totalcheckout+1)
			lended_books = LendedBook.create(name: book.title, username: user.name, date_of_lend: Date.today.to_s, user_id: user.id, book_id: book.id, status: "Holding")
			status = "Approved"
			request.update(status: status)
			redirect_to request_admin_path("lend"), notice: "Request Approved"
		else
			redirect_to request_admin_path("lend"), notice: "Book is not available right now"
		end
	end

	def reject_lend
		request = Request.find(params[:id])
		request.update(status: "Rejected")
		redirect_to request_admin_path("lend"), notice: "Request Rejected"
	end

	def approve_return
		request = Request.find(params[:id])
		book = Book.find(request.book_id)
		if book.totalBooks != book.availableBooks
			book.update(availableBooks: book.availableBooks+1)
			lended_book = LendedBook.find(request.lended_book_id)
			lended_book.update(status: "Returned")
			status = "Approved"
		else
			status = "Pending"
		end
		request.update(status: status)

		redirect_to request_admin_path("return"), notice: "Request Approved"
	end

	def reject_return
		request = Request.find(params[:id])
		lended_book = LendedBook.find(request.lended_book_id)
		lended_book.update(status: "Holding")
		request.update(status: "Rejected")
		redirect_to request_admin_path("return"), notice: "Request Rejected"
	end

#-------------------------------
	
	def approveReturnRequest
		returnRequest = ReturnRequest.find(params[:id])
		book = Book.find(returnRequest.book_id)
		if book.totalBooks != book.availableBooks
			book.update(availableBooks: book.availableBooks+1)
			#LendedBook.find(returnRequest.lended_book_id).destroy
			lendedBooks = LendedBook.find(returnRequest.lended_book_id)
			lendedBooks.update(status: "Returned")
			status = "Approved"
		else
			status = "Pending"
		end
		returnRequest.update(status: status)

		redirect_to return_all_requests_path, notice: "Request Approved"
	end

	def rejectReturnRequest
		returnRequest = ReturnRequest.find(params[:id])
		lendedBook = LendedBook.find(returnRequest.lended_book_id)
		lendedBook.update(status: "Holding")
		returnRequest.update(status: "Rejected")
		redirect_to return_all_requests_path, notice: "Request Rejected"
	end


end

app/helpers/request_admins_helper.rb
module RequestAdminsHelper
end

app/views/request_admins/approved.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<h1 style="color: #000; background-color: rgba(230, 0, 0,0.5); height: 40px;"> <%= @type.capitalize %> Book Requests </h1>
			<div class="lendBookTabs">
				<%= link_to request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						All Requests
					</div>
				<% end %>
				<%= link_to pending_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Pending Requests
					</div>
				<% end %>
				<%= link_to approved_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTabActive">
						Approved Requests
					</div>
				<% end %>
				<%= link_to rejected_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Rejected Requests
					</div>
				<% end %>
			</div>

			<br><br>

			<div class= "lendBookBox"> 
				<% if @requests.empty? %>
				<br><br><br>
					<h1> No Requests for <%= @type %>ing Books </h1>
				<% else %>
				<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> Book </th>
							<th id="t3"> User </th>
							<th id="t4"> Available <br> Books </th>
							<th id="t5"> Status </th>
						</tr>
					<% count = ((params[:page] || 1).to_i - 1) * 5%>
					<% @requests.each_with_index do |request, index| %>
						<% book = @books.find(request.book_id) %>
						<tr>
							<td> <%= count + index + 1%> </td>
							<td> <%= book.title %> </td>
							<td> <%= @users.find(request.user_id).email %> </td>
							<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
							<td> <%= request.status %> </td>
						</tr>
					<% end %>
				</table>
				<% end %>
				
			</div>
			<br>
			<%= will_paginate @requests, class: "digg_pagination" %>

		</center>


	</div>


	<br><br><br><br><br><br><br><br><br>

</div>

app/views/request_admins/index.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" > 
		<a href="<%= request_admin_path('lend') %>" >
			<div class="librarianThumbnail" style="background: url('/assets/Requests.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;">
				<p>Lend Book Requests</p>
			</div>
		</a>

		<a href="<%= request_admin_path('return') %>" >
			<div class="librarianThumbnail" style="background: url('/assets/Requests.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;">
				<p>Return Book Requests</p>
			</div>
		</a>



	</div>


	<br><br><br><br><br><br><br><br><br>

</div>

app/views/request_admins/pending.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<h1 style="color: #000; background-color: rgba(230, 0, 0,0.5); height: 40px;"> <%= @type.capitalize %> Book Requests </h1>
			<div class="lendBookTabs">
				<%= link_to request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						All Requests
					</div>
				<% end %>
				<%= link_to pending_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTabActive">
						Pending Requests
					</div>
				<% end %>
				<%= link_to approved_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Approved Requests
					</div>
				<% end %>
				<%= link_to rejected_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Rejected Requests
					</div>
				<% end %>
			</div>

			<br><br>

			<div class= "lendBookBox"> 
				<% if @requests.empty? %>
				<br><br><br>
					<h1> No Requests for <%= @type %>ing Books </h1>
				<% else %>
				<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> Book </th>
							<th id="t3"> User </th>
							<th id="t4"> Available <br> Books </th>
							<th id="t5"> Status </th>
							<th id="t6"> Action </th>
						</tr>
					<% count = ((params[:page] || 1).to_i - 1) * 5 %>
					<% @requests.each_with_index do |request, index| %>
						<% book = @books.find(request.book_id) %>
						<tr>
							<td> <%= count + index + 1%> </td>
							<td> <%= book.title %> </td>
							<td> <%= @users.find(request.user_id).email %> </td>
							<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
							<td> <%= request.status %> </td>
							<td>
								<% if request.status == "Pending" %>
									<% if @type == "lend" %>
										<%= link_to "Approve", approve_lend_request_admin_path(request) %>
										/
										<%= link_to "Reject", reject_lend_request_admin_path(request) %>
									<% elsif @type == "return" %>
										<%= link_to "Approve", approve_return_request_admin_path(request) %>
										/
										<%= link_to "Reject", reject_return_request_admin_path(request) %>
									<% end %>

								<% else %>
									No Action 
								<% end %>
							</td>
						</tr>
					<% end %>
				</table>
				<% end %>
				
			</div>
			<br>
			<%= will_paginate @requests, class: "digg_pagination" %>

		</center>


	</div>


	<br><br><br><br><br><br><br><br><br>

</div>

app/views/request_admins/rejected.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<h1 style="color: #000; background-color: rgba(230, 0, 0,0.5); height: 40px;"> <%= @type.capitalize %> Book Requests </h1>
			<div class="lendBookTabs">
				<%= link_to request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						All Requests
					</div>
				<% end %>
				<%= link_to pending_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Pending Requests
					</div>
				<% end %>
				<%= link_to approved_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Approved Requests
					</div>
				<% end %>
				<%= link_to rejected_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTabActive">
						Rejected Requests
					</div>
				<% end %>
			</div>

			<br><br>

			<div class= "lendBookBox"> 
				<% if @requests.empty? %>
				<br><br><br>
					<h1> No Requests for <%= @type %>ing Books </h1>
				<% else %>
				<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> Book </th>
							<th id="t3"> User </th>
							<th id="t4"> Available <br> Books </th>
							<th id="t5"> Status </th>
						</tr>
					<% count = ((params[:page] || 1).to_i - 1) * 5 %>
					<% @requests.each_with_index do |request, index| %>
						<% book = @books.find(request.book_id) %>
						<tr>
							<td> <%= count + index + 1%> </td>
							<td> <%= book.title %> </td>
							<td> <%= @users.find(request.user_id).email %> </td>
							<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
							<td> <%= request.status %> </td>
						</tr>
					<% end %>
				</table>
				<% end %>
				
			</div>
			<br>
			<%= will_paginate @requests, class: "digg_pagination" %>

		</center>


	</div>


	<br><br><br><br><br><br><br><br><br>

</div>

app/views/request_admins/show.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<h1 style="color: #000; background-color: rgba(230, 0, 0,0.5); height: 40px;"> <%= @type.capitalize %> Book Requests </h1>
			<div class="lendBookTabs">
				<%= link_to request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTabActive">
						All Requests
					</div>
				<% end %>
				<%= link_to pending_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Pending Requests
					</div>
				<% end %>
				<%= link_to approved_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Approved Requests
					</div>
				<% end %>
				<%= link_to rejected_request_admin_path(@type), class: "lendBookTabAnchor" do %>
					<div class="lendBookTab">
						Rejected Requests
					</div>
				<% end %>
			</div>

			<br><br>

			<div class= "lendBookBox"> 
				<% if @requests.empty? %>
				<br><br><br>
					<h1> No Requests for <%= @type %>ing Books </h1>
				<% else %>
				<table>
						<tr>
							<th id="t1"> S.No. </th>
							<th id="t2"> Book </th>
							<th id="t3"> User </th>
							<th id="t4"> Available <br> Books </th>
							<th id="t5"> Status </th>
							<th id="t6"> Action </th>
						</tr>
					<% count = ((params[:page] || 1).to_i - 1) * 5 %>
					<% @requests.each_with_index do |request, index| %>
						<% book = Book.find(request.book_id) %>
						<tr>
							<td> <%= count + index + 1%> </td>
							<td> <%= book.title %> </td>
							<td> <%= User.find(request.user_id).email %> </td>
							<td> <%= book.availableBooks %>/<%= book.totalBooks %> </td>
							<td> <%= request.status %> </td>
							<td>
								<% if request.status == "Pending" %>
									<% if @type == "lend" %>
										<%= link_to "Approve", approve_lend_request_admin_path(request) %>
										/
										<%= link_to "Reject", reject_lend_request_admin_path(request) %>
									<% elsif @type == "return" %>
										<%= link_to "Approve", approve_return_request_admin_path(request) %>
										/
										<%= link_to "Reject", reject_return_request_admin_path(request) %>
									<% end %>

								<% else %>
									No Action 
								<% end %>
							</td>
						</tr>
					<% end %>
				</table>
				<% end %>
				
			</div>
			<br>
			<%= will_paginate @requests, class: "digg_pagination" %>

		</center>


	</div>


	<br><br><br><br><br><br><br><br><br>

</div>