config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home', as: :home
  devise_for :users 
  get '/show_user/:id' => 'pages#show_user', as: :show_user

  resources :books do 
    collection do
      get 'lend_requests'
      get 'return_requests'
      get 'lended_list'
      get 'searched_index'
      get 'thank'
    end
    get 'lend', on: :member
    get 'return', on: :member
  end

  resources :librarians, only: [:index, :show] do 
    get 'books', on: :collection
  end

  resources :user_admins, only: [:index, :show, :destroy]
  resources :request_admins, only: [:index, :show] do
    member do
      get 'pending'
      get 'approved'
      get 'rejected'
      get 'approve_lend'
      get 'reject_lend'
      get 'approve_return'
      get 'reject_return'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController
	before_action :authenticate_user!
	def index

	end

	def books
		@books = Book.paginate(page: params[:page], per_page: 9)
	end

	def show #show book details
		@book = Book.find(params[:id])
	end

	

	private
	def book_params
		params.require(:book).permit(:title, :author, :publisher, :language, :description, :image, :totalBooks, :availableBooks)
	end

end

app/helpers/librarians_helper.rb
module LibrariansHelper
end

app/views/librarians/books.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>


	<div class="librarianContainer" >
		<center>
			<div class="librarianIndexBox">
				<table >
					<tr>
						<th>S.No.</th>
						<th>Name</th>
					</tr>
					<% count = ((params[:page]||1).to_i - 1) * 10 %>
					<% @books.each_with_index do |book, index| %>
						<tr>
							<td> <%= count + index + 1 %></td>
							<td> <%= link_to book.title, librarian_path(book) %> </td>
						</tr>
					<% end %>

				</table>
			</div>
			<br><br>
			<%= will_paginate @books, class: "digg_pagination" %>
		</center>
	</div>



	<br><br><br><br><br><br><br><br><br>

	
	<div class="footer">
		Visit Soon
	</div>
</div>

app/views/librarians/index.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>

	<div class="librarianContainer" >

		<% if current_user.role=="request_manager" %>
			<a href="<%= request_admins_path %>" >
				<div class="librarianThumbnail" style="background: url('/assets/Requests.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;">
					<p>Requests</p>
				</div>
			</a>
		<% end %>
		<% if current_user.role=="book_manager" %>
			<a href="<%= new_book_path %>">
				<div class="librarianThumbnail" style="background: url('/assets/AddBook.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;" >
					<p>Add Book</p>
				</div>
			</a>

			<a href="<%= books_librarians_path %>" >
				<div class="librarianThumbnail" style="background: url('/assets/SeeBooks.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;">
					<p>See Books</p>
				</div>
			</a>
		<% end %>

		<a href="<%= user_admins_path %>">
			<div class="librarianThumbnail" style="background: url('/assets/Users.jpg'); background-repeat: no-repeat; background-position: center; background-size: auto;">
				<p>See All users</p>
			</div>
		</a>

		
	</div>


	<br><br><br><br><br><br><br><br><br>

</div>

app/views/librarians/show.html.erb
<div class="fullPage" >
	<div class="header" >
		<%= link_to image_tag('/assets/bookLogo.jpg'), librarians_path , :class=>'logo' %>

		<center>
			<h1 > LIBRARY MANAGEMENT SYSTEM</h1>
			<p> A platform to search your favorite book </p>
		</center>
		<div class="tab">
			<div class="contents">
				Welcome, <%= current_user.name %> <font color="black">(<%= current_user.role.humanize %>)</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


				<%= link_to 'LogOut', destroy_user_session_path, method: :delete %>
				&nbsp;&nbsp;&nbsp;&nbsp;
			</div>

		</div>

	</div>

	<div class="librarianContainer" >
		<center>
			<div class="showBlock" >
					<img src="<%=@book.image %>" >
			</div>
			<div class="showDetails">
				<h2>Book Details</h2>
				<table class="bookDetails">
					<tr>
						<td class="TableTag">Title</td>
						<td> : </td>
						<td> <%= @book.title %> </td>
					</tr>
					<tr>
						<td class="TableTag">Author</td>
						<td> : </td>
						<td> <%= @book.author %> </td>
					</tr>
					<tr>
						<td class="TableTag">Publisher </td>
						<td> : </td>
						<td> <%= @book.publisher %> </td>
					</tr>
					<tr>
						<td class="TableTag">Language</td>
						<td> : </td>
						<td> <%= @book.language %> </td>
					</tr>
					<tr>
						<td class="TableTag">Description</td>
						<td> : </td>
						<td> <%= @book.description %> </td>
					</tr>
					<tr>
						<td class="TableTag">Available Books</td>
						<td>:</td>
						<td> <%= @book.availableBooks %></td>
					</tr>
					<tr>
						<td class="TableTag">Total Books</td>
						<td>:</td>
						<td> <%= @book.totalBooks %></td>
					</tr>

				</table>

			</div>
			<%= link_to "Edit", edit_book_path(@book) , class: 'button' %>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to "Remove Book", book_path(@book.id), method: :delete, class: 'button' %>
		</center>
	</div>


	<br><br><br><br><br><br><br><br><br>

	<div class="footer">
		Visit Soon
	</div>
</div>